require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'lib/generators/**/*'
    - 'lib/grpc/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 15

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray: # Drew & Edu discussed it and decided to turn this off, because of ugly multiline `%w[` styled arrays
  Enabled: false

Style/IfUnlessModifier: # Drew & Edu discussed it and decided to turn this off
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
